basePath: /
consumes:
    - application/json
definitions:
    Product:
        x-go-package: github.com/codepnw/microservices/api/data
info:
    description: Documentation for Product API
    title: Product API
    version: 1.0.0
paths:
    /products:
        get:
            description: Return a list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            tags:
                - products
        post:
            description: Create a new product
            operationId: createProduct
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
            tags:
                - products
        put:
            description: Update a products details
            operationId: updateProduct
            responses:
                "201":
                    $ref: '#/responses/noContentResponse'
            tags:
                - products
    /products/{id}:
        delete:
            description: Return a list of products
            operationId: deleteProduct
            parameters:
                - format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "201":
                    $ref: '#/responses/noContentResponse'
            tags:
                - products
produces:
    - application/json
responses:
    noContentResponse:
        description: ""
    productResponse:
        description: ""
    productsResponse:
        description: ""
        schema:
            items: {}
            type: array
schemes:
    - http
swagger: "2.0"
